language: node_js
node_js: 20
dist: jammy
cache: yarn
branches:
  only:
    - master
     # detect also tag like x.y.z or x.y.z-beta.n as travis consider them to be branches
    - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
env:
  global:
    - MATTERMOST_CHANNEL='{"dev":"app-photos","beta":"app-photos,publication","stable":"app-photos,publication"}'
    # MATERMOST_HOOK_URL for post on mattermost
    - secure: "n2woUawe27+dU7pRl5aM3lTHpEKoLMpFNXBJPOVeBV/lNl+I0HDYMPJGNRBZKeYRvCBimHKiq2lcNnKLAG9FOeVfDdoxLDeLbIOT4h+PphN1Z0NdIRav4q9HEz1L044+bfF9jYVWizBNTMxpDv74i43qge6eh+BJp8OynVEtrH23XczE2qBgWqcoZSN3zQFJDq5e7s5Rk0x1pl7hqvutoWXT41gP021mCSj7sqVlEj0LG0wESFMz13ja74PbNHJTLYiK0oKpmsnrUabPJxWaNyNbfe4wYCB4ctniMXvpF6Yy79bvmkqpbWiNo7+9pphlo0xlBB0s2/g/diWVEOV+ia+ctfcl8JQizt4pCCWE3rkboYSOMVkVWiBy9OC6KghG0hhevYkLIihRuBaD7m8piaJ/XPwrX5rVdF/oE2CllpuHNdccxaLs8QXataCZZEsYfdE+9A1wLamrqJi3G4rhcI3cHIT4d15mnEySK/Vzhvy1dlpkUxUQJreuKxMqZ95BsRK6nnS97Cqxlvw4QfIszJ4cIwvbPukaeMhymYOdfo1YgTcMpFNsoP7HjBNGgHWPxG0WYt35cs3lU66nsY/hTpD8P0ymzWVFrb/DQMcliJWh0+CRx/e1PIAgYju7x7m2cXXamMx3Pvkr9+HqYCZ5OLn8GcxE7nLcVjHKic3Vv+c="
    # REGISTRY_TOKEN for yarn cozyPublish script
    - secure: "U6H8M/733c/b0z9q6wMdX7XdkS4PTrqKg1byN7tkowsmbJ+SNv8MI4K/l8fPzJuy5gl0nBe02X69+y3j6Cm5NajzarDt0E7QtlfdR6YfRowCjt2n3sYLak9F2cPdDw1H29j2U1DG/G275KtRV3ble44LMbHOa8pQB1az+iqcDGlLATjT2AH5vmDC3F1EYJzOwHuNNQGPl+bgIJvfdF1TAv25QdEP2tiEmhBZnNLkonMnv8xdoUxjXkjRjlpYfzrOeTJPISbs9I/PrBx3NnTukrGpkqQKZsMlA05qovVZ451/fpL2X7VIR9WxRfOnjebwiTlArRNkb3kPbCEOLBKAfhWVCyZBFTh3INMIdDPt4ByAitEmC3dPrFDlgzpHb2qj5QqY+6FywbvkZs9F2tq6zRyaC5RzHgqbiGt89pwlPnN0HF0ZARmhk102z76ndBPnkCsIGJVP9OYStu7IgJqeiswDOrObOoBiEEOmBHst/D9sLogzrj219ESPFFVrJ/UZYs3iKmGgiPk72o2XxyqU/O/R7gaeXs/rmjAIfEZPFmLIOjKzrpIQSYYKnFYhwW45wMjSP68wvF/g6Yc/M8AhvyFh4pHltTG289m51kCA+OlKVVJUn2KW2GBrcwty1RFfzIVjljecPkVpWIC1EZnTmuDO5SalVLTPz91TkapVS4A="
    # GITHUB_TOKEN for yarn deploy script
    - secure: "ehPYnxOj7SegMePl8XXxQBxoBSh+UWKQQitwVNEy9dnKAsYgNEcb0XfG1uLy1v596NcyifVjxEDs93aDF4kZT/0AWH67re7XZpqCyy+wJt7oMJ6YKPoCLR9Zs1VG2jD/OTmkT4zT7VzAqUGkhyz6k+tYwFazeWXPqAfbyA7Q2fa7etzzi0A/oruKKD3Gof2AMGiYOKhTmCwdBbcFEsBNkgc+nzEh/lH9iEL/b86EXS5VKHpDAEsJI0+Z2gY8vX8MBRk5sHlsKaf9F1KTUGZHCEXZ9nrMe3+0nGXSzNydK2Tf3He2zLqXSwZjp74u1ZW5EzF5zzQPp5irnip6pk3dZkaAO56mHoY24cmcX+BvxzJSeLapnnuRYWQKyexOp0sFFUsMBvoURH8prxXS17jxu4whCMAUH4XSf2Yvf0P1GhIV9JIZzdxxJkIgIBmcAcjYvDqBHqfBk2p44TRtBnUcE56WUDWeFLVqPbBldma80aJgdQ3/ShkDmkecsxHxMapACFR4jnFAR9kYUtP1sQbdO/MyhBf9bmHiqRiAjjHOiKLBIvHTM/BrR3kO6fv1xTx6INYyfJSwg5uhqdyGPFlNaWG5CiEJx80giP3n7hIjQ3kVpwx5Dh02bmhZ3I6GMUo/OkFM11FBnx84RgRG/tt3VVIpmQsuYjQBZ/Rzs3UBZQo="
stages:
  - prebuild
  - build
jobs:
  include:
    - name: 'Lint'
      stage: 'prebuild'
      script: yarn lint
    - name: 'Unit tests node 16'
      stage: 'prebuild'
      node_js: 16
      script: yarn test
    - name: 'Unit tests node 20'
      stage: 'prebuild'
      node_js: 20
      script: yarn test
    - name: 'Build app'
      stage: 'build'
      before_script:
        - '[ "$TRAVIS_SECURE_ENV_VARS" != "false" ] && openssl aes-256-cbc -K $encrypted_497d1a9dc404_key -iv $encrypted_497d1a9dc404_iv -in id_rsa_downcloud_photos.enc -out id_rsa_downcloud_photos -d'
        - '[ "$TRAVIS_SECURE_ENV_VARS" != "false" ] && eval "$(ssh-agent -s)"'
        - '[ "$TRAVIS_SECURE_ENV_VARS" != "false" ] && chmod 600 id_rsa_downcloud_photos'
        - '[ "$TRAVIS_SECURE_ENV_VARS" != "false" ] && ssh-add id_rsa_downcloud_photos'
      script:
        - yarn build
      before_deploy:
        - yarn add cozy-app-publish # to be sure to have the last version before deploy
      deploy:
        - &deploy
          provider: script
          repo: cozy/cozy-photos
          skip-cleanup: true
          script: yarn run deploy
          on:
            # deploy the build on a build branch and publish to the Cozy registry
            branch: master
        - <<: *deploy
          on:
            # publish stable or beta versions using Github Releases (git tag)
            tags: true
